name: YAML Lint

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install tools
        run: uv tool install "yamllint==1.38.0"

      - name: Run yamllint
        run: yamllint .github/workflows
